name: Clickable Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut
      - name: Build
        run: |
          CLICKABLE_FRAMEWORK=ubuntu-sdk-20.04 clickable build --arch all
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Logviewer
          path: build/all/app/*.click
          if-no-files-found: error
